version: '2'

services:
  app:
    container_name: app
    image: chat:dev
    build:
      context: .
      args:
        VERSION: dev
    environment:
      # PORT must be always 8080 and need only for back compatibility with Heroku
      PORT: 8080
    ports:
      - "80:8080"
    volumes:
      - ./:/var/www/app
      - ./_dev/conf/:/var/www/app/conf/:ro
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./_docker/db/data:/var/lib/mysql
      - ./_docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      #PMA_HOST: sql4.freemysqlhosting.net
