version: '2'

services:
  fpm-app:
    container_name: fpm-app
    image: chat:dev
    build:
      context: .
      args:
        VERSION: dev
    depends_on:
      - memcached
    environment:
      PHP_SESSION_SERVERS: memcached:11211
    volumes:
      - ./:/app/
      - ./_dev/conf/:/app/conf/:ro
    network_mode: service:nginx
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"          # http
    volumes:
      - ./:/var/www/:ro
      - ./_dev/nginx/app.vhost.conf:/etc/nginx/conf.d/default.conf:ro
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./_docker/db/data:/var/lib/mysql
      - ./_docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
  memcached:
    container_name: memcached
    image: memcached:alpine
    command: -m 4 -v
    expose:
      - "11211"    # memcache
