name: Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Docker to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_app_name: php-sandbox-${{ github.repository_owner }}
          usedocker: true
          appdir: "."
        env:
          HD_CONF_MYSQL_HOST: "sql4.freemysqlhosting.net"
          HD_CONF_MYSQL_DB: ${{ secrets.MYSQL_USER }}
          HD_CONF_MYSQL_USER: ${{ secrets.MYSQL_USER }}
          HD_CONF_MYSQL_PASS: ${{ secrets.MYSQL_PASS }}
